package application;

import static application.Tile2D.*;

public class Config {
	/*2D maps*/
	public static Tile2D[][] map1 = {
            {TREE_GRASS_METAL_FENCE_LEFT_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_METAL_FENCE_RIGHT_DARKER},
            {METAL_FENCE_LEFT_DIRT, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, METAL_FENCE_RIGHT_DIRT},
            {METAL_FENCE_LEFT_DIRT, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, METAL_FENCE_RIGHT_DIRT},
            {METAL_FENCE_LEFT_DIRT, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, METAL_FENCE_RIGHT_DIRT},
            {METAL_FENCE_LEFT_DIRT, GRASS, GRASS, BUSH_GRASS_TILE, HOUSE_UPPER_LEFT_GRASS, HOUSE_UPPER_RIGHT_GRASS, BUSH_GRASS_TILE, GRASS, GRASS, METAL_FENCE_RIGHT_DIRT},
            {METAL_FENCE_LEFT_DIRT, GRASS, GRASS, BUSH_GRASS_TILE, HOUSE_LOWER_LEFT_GRASS, HOUSE_LOWER_RIGHT_GRASS, BUSH_GRASS_TILE, GRASS, GRASS, METAL_FENCE_RIGHT_DIRT},
            {METAL_FENCE_LEFT_DIRT, GRASS, GRASS, ROCK_GRASS, PAVEMENT, GRASS, GRASS, GRASS, GRASS, METAL_FENCE_RIGHT_DIRT},
            {METAL_FENCE_LEFT_DIRT, GRASS, GRASS, GRASS, PAVEMENT, GRASS, GRASS, GRASS, GRASS, METAL_FENCE_RIGHT_DIRT},
            {METAL_FENCE_LEFT_DIRT, GRASS, GRASS, GRASS, PAVEMENT, GRASS, GRASS, GRASS, GRASS, METAL_FENCE_RIGHT_DIRT},
            {METAL_FENCE_GRASS, METAL_FENCE_GRASS, METAL_FENCE_GRASS, METAL_FENCE_GRASS, PAVEMENT, METAL_FENCE_GRASS, METAL_FENCE_GRASS, METAL_FENCE_GRASS, METAL_FENCE_GRASS, METAL_FENCE_GRASS}
    };
	public static Tile2D[][] map2 = {
            {TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER},
            {TREE_GRASS_DARKER, GRASS_DARKER_HOLE, GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, TREE_GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, TREE_GRASS_DARKER},
            {TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, DIRT, TREE_GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, TREE_GRASS_DARKER},
            {TREE_GRASS_DARKER, GRASS_DARKER, DIRT, DIRT, DIRT, TREE_GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, TREE_GRASS_DARKER},
            {TREE_GRASS_DARKER, GRASS_DARKER, TREE_GRASS_DARKER, ROCK_DIRT, DIRT, TREE_GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, TREE_GRASS_DARKER},
            {TREE_GRASS_DARKER, GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, TREE_GRASS_DARKER},
            {TREE_GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, TREE_GRASS_DARKER, DIRT, DIRT, DIRT, TREE_GRASS_DARKER},
            {TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, GRASS_DARKER, TREE_GRASS_DARKER, ROCK_DIRT, DIRT, ROCK_DIRT, TREE_GRASS_DARKER},
            {TREE_GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, TREE_GRASS_DARKER, ROCK_DIRT, GRASS_DARKER_HOLE, ROCK_DIRT, TREE_GRASS_DARKER},
            {TREE_GRASS_DARKER, GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER}
    };
	
	/*characters*/
	public static TileCharacter[][] characters1 = new TileCharacter[10][10];
}
