package application;

import static application.Tile2D.*;
import static application.TileCharacter.*;

public class Config {
	/*2D maps*/
	public static Tile2D[][][] maps = {
			{
	            {TREE_GRASS_METAL_FENCE_LEFT_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_METAL_FENCE_RIGHT_DARKER},
	            {METAL_FENCE_LEFT_DIRT, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, METAL_FENCE_RIGHT_DIRT},
	            {METAL_FENCE_LEFT_DIRT, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, METAL_FENCE_RIGHT_DIRT},
	            {METAL_FENCE_LEFT_DIRT, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, METAL_FENCE_RIGHT_DIRT},
	            {METAL_FENCE_LEFT_DIRT, GRASS, GRASS, BUSH_GRASS_TILE, HOUSE_UPPER_LEFT_GRASS, HOUSE_UPPER_RIGHT_GRASS, BUSH_GRASS_TILE, GRASS, GRASS, METAL_FENCE_RIGHT_DIRT},
	            {METAL_FENCE_LEFT_DIRT, GRASS, GRASS, BUSH_GRASS_TILE, HOUSE_LOWER_LEFT_GRASS, HOUSE_LOWER_RIGHT_GRASS, BUSH_GRASS_TILE, GRASS, GRASS, METAL_FENCE_RIGHT_DIRT},
	            {METAL_FENCE_LEFT_DIRT, GRASS, GRASS, ROCK_GRASS, PAVEMENT, GRASS, GRASS, GRASS, GRASS, METAL_FENCE_RIGHT_DIRT},
	            {METAL_FENCE_LEFT_DIRT, GRASS, GRASS, GRASS, PAVEMENT, GRASS, GRASS, GRASS, GRASS, METAL_FENCE_RIGHT_DIRT},
	            {METAL_FENCE_LEFT_DIRT, GRASS, GRASS, GRASS, PAVEMENT, GRASS, GRASS, GRASS, GRASS, METAL_FENCE_RIGHT_DIRT},
	            {METAL_FENCE_GRASS, METAL_FENCE_GRASS, METAL_FENCE_GRASS, METAL_FENCE_GRASS, PAVEMENT, METAL_FENCE_GRASS, METAL_FENCE_GRASS, METAL_FENCE_GRASS, METAL_FENCE_GRASS, METAL_FENCE_GRASS}
			},{			
        {TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER},
        {TREE_GRASS_DARKER, GRASS_DARKER_HOLE, GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, TREE_GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, TREE_GRASS_DARKER},
        {TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, DIRT, TREE_GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, TREE_GRASS_DARKER},
        {TREE_GRASS_DARKER, GRASS_DARKER, DIRT, DIRT, DIRT, TREE_GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, TREE_GRASS_DARKER},
        {TREE_GRASS_DARKER, GRASS_DARKER, TREE_GRASS_DARKER, ROCK_DIRT, DIRT, TREE_GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, TREE_GRASS_DARKER},
        {TREE_GRASS_DARKER, GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, TREE_GRASS_DARKER},
        {TREE_GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, TREE_GRASS_DARKER, DIRT, DIRT, DIRT, TREE_GRASS_DARKER},
        {TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, GRASS_DARKER, TREE_GRASS_DARKER, ROCK_DIRT, ROCK_DIRT, DIRT, TREE_GRASS_DARKER},
        {TREE_GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, GRASS_DARKER, TREE_GRASS_DARKER, ROCK_DIRT, GRASS_DARKER_HOLE, DIRT, TREE_GRASS_DARKER},
        {TREE_GRASS_DARKER, GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER, TREE_GRASS_DARKER}
			}
		};
	/*map end locations*/
	public static int[][] mapStartEnd = {
			{PLAYER.getLocX(),PLAYER.getLocY(), 0, 7},
			{9,1,-1,-1}
	};
	/*characters*/
	public static TileCharacter[][] characters = new TileCharacter[10][10];
	
	/*characters per level*/
	public static TileCharacter[][] charPerLevel = {
			{PLAYER},
			{PLAYER, DOG}
	};
}
